<?php
// CLI-only tool to create or reset an admin account.
//
// Usage:
//   php admin/create-admin.php <username> <password>
//
// Writes/updates data/admin-users.php. Run this once during setup, and
// again any time you need to add an admin or reset a forgotten password —
// there's no "forgot password" flow in the web UI by design, since this is
// a small single-site admin panel, not a multi-tenant system.

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    exit('This script can only be run from the command line.');
}

if ($argc < 3) {
    fwrite(STDERR, "Usage: php create-admin.php <username> <password>\n");
    exit(1);
}

$username = $argv[1];
$password = $argv[2];

if (strlen($password) < 8) {
    fwrite(STDERR, "Password must be at least 8 characters.\n");
    exit(1);
}

$dataDir = dirname(__DIR__) . '/data';
if (!is_dir($dataDir)) {
    mkdir($dataDir, 0750, true);
}

$usersFile = "$dataDir/admin-users.php";
$users = is_file($usersFile) ? require $usersFile : [];

$users[$username] = [
    'password_hash' => password_hash($password, PASSWORD_DEFAULT),
    'created_at'    => isset($users[$username]) ? $users[$username]['created_at'] : date('c'),
    'updated_at'    => date('c'),
];

$export = "<?php\n// Admin accounts for /admin/. Generated by admin/create-admin.php —\n// do not edit by hand. Never commit this file to a public repository.\nreturn " . var_export($users, true) . ";\n";

file_put_contents($usersFile, $export);
chmod($usersFile, 0640);

echo "Admin account '$username' saved to data/admin-users.php\n";
